server.port=8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolBooks

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.use-new-id-generator-mappings=false
#
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=false

## MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB


#File
pgAdmission.file.image.photo-height: 300
pgAdmission.file.image.signature-height: 80
pgAdmission.file.image.width: 300
pgAdmission.file.image.max-image-size: 50
pgAdmission.file.max-document-size: 10000
pgAdmission.file.image.photo-destination: ${PG_PHOTO_DESTINATION}
pgAdmission.file.image.signature-destination: ${PG_SIGNATURE_DESTINATION}
pgAdmission.file.image.file-destination: ${PG_FILE_DESTINATION}
pgAdmission.iums.url: ${UMS_BANK_API}
# http://localhost:8080/ums-webservice-bank