version: '3.6'
services:
  pgadmission-app:
    image: pgadmission
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:oracle:thin:@103.23.42.69:1521:prod
      - DB_USERNAME=DB_IUMS_PG_ADMISSION
      - DB_PASSWORD=ig100
      - PG_PHOTO_DESTINATION=opt/pg/photo
      - PG_SIGNATURE_DESTINATION=opt/pg/signature
      - PG_FILE_DESTINATION=opt/pg/file
      - UMS_BANK_API=http://localhost:8080/ums-webservice-bank
      - PG_SLEEP=3 # gives time for other services to boot before the application
    ports:
      - "8082:8082"
